AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: YouTube search API using Lambda, HTTP API Gateway, Secrets Manager, and SNS notification

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  YoutubeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: youtube-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionWithSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:*:*:secret:youtube/*

  YoutubeHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: YoutubeSearchHttpApi
      CorsConfiguration:
        AllowMethods: ["GET"]
        AllowOrigins: ["*"]

  YoutubeSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: youtubeSearchLambda
      Handler: handler.lambda_handler
      Runtime: python3.11
      CodeUri: lambda.zip
      MemorySize: 256
      Timeout: 30
      Role: !GetAtt YoutubeLambdaRole.Arn
      Environment:
        Variables:
          YOUTUBE_API_SECRET_NAME: youtube/api/key
      Events:
        SearchAPI:
          Type: HttpApi
          Properties:
            Path: /search
            Method: GET
            ApiId: !Ref YoutubeHttpApi

  DeploymentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DeployNotificationTopic
      Subscription:
        - Protocol: email
          Endpoint: joseph.siyi@gmail.com

Outputs:
  ApiEndpoint:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${YoutubeHttpApi}.execute-api.${AWS::Region}.amazonaws.com/search"
