AWSTemplateFormatVersion: '2010-09-09'
Description: YouTube search API with Lambda, API Gateway, and Secrets Manager

Parameters:
  LambdaS3Bucket:
    Type: String
    Default: youtube-api-artifacts-joseph
    Description: The name of the S3 bucket containing the Lambda zip

  LambdaS3Key:
    Type: String
    Default: lambda.zip
    Description: The S3 object key (path to the lambda.zip)

Resources:
  YoutubeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: youtube-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionWithSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:*:*:secret:*

  YoutubeApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: YoutubeSearchHttpApi
      CorsConfiguration:
        AllowMethods: ["GET"]
        AllowOrigins: ["*"]
        
  YoutubeSearchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: youtubeSearchLambda
      Runtime: python3.11
      Handler: handler.lambda_handler
      Timeout: 30
      MemorySize: 256
      Role: !GetAtt YoutubeLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Environment:
        Variables:
          YOUTUBE_API_SECRET_NAME: youtube/api/key
      Events:
        SearchAPI:
          Type: HttpApi
          Properties:
            Path: /search
            Method: GET
            ApiId: !Ref YoutubeApi
            ApiKeyRequired: true

  YoutubeApiKey:
    Type: AWS::ApiGatewayV2::ApiKey
    Properties:
      Name: YoutubeHttpApiKey

  YoutubeUsagePlan:
    Type: AWS::ApiGatewayV2::UsagePlan
    Properties:
      UsagePlanName: YoutubeSearchHttpPlan
      ApiStages:
        - ApiId: !Ref YoutubeApi
          Stage: $default
      Throttle:
        RateLimit: 10
        BurstLimit: 5
      Quota:
        Limit: 1000
        Period: MONTH

  UsagePlanKey:
    Type: AWS::ApiGatewayV2::UsagePlanKey
    Properties:
      KeyId: !Ref YoutubeApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref YoutubeUsagePlan

  DeploymentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DeployNotificationTopic
      Subscription:
        - Protocol: email
          Endpoint: joseph.siyi@gmail.com

Outputs:
  ApiEndpoint:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${YoutubeApi}.execute-api.${AWS::Region}.amazonaws.com/search"

  ApiKey:
    Description: "API Key to access this endpoint"
    Value: !Ref YoutubeApiKey

